os:
  - "WMF 5"

branches:
  only:
    - master

install:
  - ps: |
      Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force
      Install-Module PackageManagement -Force -SkipPublisherCheck
      Install-Module PowershellGet -Force -SkipPublisherCheck

  - ps: |
      Install-Module Pester -Force
      Install-Module psake -Force
      Install-Module PSScriptAnalyzer -Force
      Install-Module platyPS -Force
      Install-Module PSBuild -Force -AllowPrerelease

build_script:
  - ps: |
      Invoke-Builder Stage

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))