os:
  - "WMF 5"

branches:
  only:
    - master

install:
  - ps: PowerShell -command "Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force | Out-Null; Install-Module PowershellGet -SkipPublisherCheck -Force; Install-Module PackageManagement -SkipPublisherCheck -Force"
  - ps: |
      Install-Module Pester -Force
      Install-Module psake -Force
      Install-Module PSScriptAnalyzer -Force
      Install-Module platyPS -Force
      Install-Module PSBuilder -Force -AllowPrerelease

build_script:
  - ps: |
      Invoke-Builder Stage

on_failure:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))